create table if not EXISTS request
(
    id           int generated by default as identity,
    request_text varchar not null
);

create table if not EXISTS response
(
    id           int generated by default as identity,
    response_text varchar not null
)
